"""database.models — domain-partitioned model package (Phase 3).

Permanent facade: ``from database.models import <Name>`` keeps working for
every caller. Classes were split from the former single models.py file into
per-domain modules; all import unconditionally so every table registers on
the shared Base.metadata regardless of module enable flags.
"""

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    LargeBinary,
    Numeric,
    SmallInteger,
    String,
    Text,
    Time,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, INET, JSONB, UUID

from database.connection import Base

from .core import (
    User,
    PasswordResetToken,
    IntegrationToken,
    WebhookEvent,
    BusinessProfile,
    CronRunState,
)
from .contacts import (
    Contact,
)
from .messaging import (
    NotificationJob,
    StaffNotificationEvent,
    NotificationPreference,
    NotificationSubscriber,
    NotificationSubscription,
    Conversation,
    ConversationMessage,
    ConversationRead,
    WebChatScript,
)
from .deals import (
    Event,
    LeadApplication,
    EventParticipant,
    EventStatusChangeEvent,
    EventDocument,
    Invoice,
    InvoiceOrderDiscount,
    InvoiceLineItem,
    InvoiceInstallment,
    InvoiceInvitation,
    Quote,
    QuoteOrderDiscount,
    QuoteLineItem,
    QuoteInstallment,
    QuoteInvitation,
    Payment,
    PaymentAllocation,
    RefundEvent,
    NumberingState,
    InstallmentReminderState,
)
from .inventory import (
    CatalogItem,
    SpecialOrder,
)
from .scheduling import (
    StaffLocation,
    StaffPunch,
    StaffPunchAuditEvent,
    StaffPunchCorrectionRequest,
    AttendancePreCloseReminder,
    StaffShift,
    StaffShiftOverride,
    StaffHoliday,
    TimeOffRequest,
    TimeOffDecisionEvent,
    StaffShiftRequest,
    OpenShiftPost,
    StaffShiftRequestEvent,
    RecurringUnavailability,
    StaffScheduleEntry,
    StaffSchedulePreset,
)
from .booking import (
    Appointment,
    AppointmentAvailabilityRule,
    AppointmentBlackout,
    AppointmentVisitor,
    AppointmentSessionEvent,
    AppointmentEnrichmentResponse,
    BookingWidgetThemeSettings,
    AppointmentTriedOnItem,
)
from .analytics import (
    StorefrontVisitor,
    StorefrontSession,
    StorefrontEvent,
    LeadAttribution,
    AdConversionEvent,
    ActivityLog,
    SalesActivityEvent,
    ContactCallAttempt,
)

__all__ = [
    "BigInteger",
    "Boolean",
    "Column",
    "Date",
    "DateTime",
    "ForeignKey",
    "Integer",
    "LargeBinary",
    "Numeric",
    "SmallInteger",
    "String",
    "Text",
    "Time",
    "text",
    "ARRAY",
    "INET",
    "JSONB",
    "UUID",
    "Base",
    "User",
    "PasswordResetToken",
    "IntegrationToken",
    "WebhookEvent",
    "BusinessProfile",
    "CronRunState",
    "Contact",
    "NotificationJob",
    "StaffNotificationEvent",
    "NotificationPreference",
    "NotificationSubscriber",
    "NotificationSubscription",
    "Conversation",
    "ConversationMessage",
    "ConversationRead",
    "WebChatScript",
    "Event",
    "LeadApplication",
    "EventParticipant",
    "EventStatusChangeEvent",
    "EventDocument",
    "Invoice",
    "InvoiceOrderDiscount",
    "InvoiceLineItem",
    "InvoiceInstallment",
    "InvoiceInvitation",
    "Quote",
    "QuoteOrderDiscount",
    "QuoteLineItem",
    "QuoteInstallment",
    "QuoteInvitation",
    "Payment",
    "PaymentAllocation",
    "RefundEvent",
    "NumberingState",
    "InstallmentReminderState",
    "CatalogItem",
    "SpecialOrder",
    "StaffLocation",
    "StaffPunch",
    "StaffPunchAuditEvent",
    "StaffPunchCorrectionRequest",
    "AttendancePreCloseReminder",
    "StaffShift",
    "StaffShiftOverride",
    "StaffHoliday",
    "TimeOffRequest",
    "TimeOffDecisionEvent",
    "StaffShiftRequest",
    "OpenShiftPost",
    "StaffShiftRequestEvent",
    "RecurringUnavailability",
    "StaffScheduleEntry",
    "StaffSchedulePreset",
    "Appointment",
    "AppointmentAvailabilityRule",
    "AppointmentBlackout",
    "AppointmentVisitor",
    "AppointmentSessionEvent",
    "AppointmentEnrichmentResponse",
    "BookingWidgetThemeSettings",
    "AppointmentTriedOnItem",
    "StorefrontVisitor",
    "StorefrontSession",
    "StorefrontEvent",
    "LeadAttribution",
    "AdConversionEvent",
    "ActivityLog",
    "SalesActivityEvent",
    "ContactCallAttempt",
]
